# -*- coding: utf-8 -*-
"""new machine l

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CaK2tOp2Vfl2lmTtIy5T4A8aELbVt2v
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/SBI Dataset.csv , new.csv")

df

df.head()

df.info()

df.describe()

df.describe()

df.hist(figsize=(10,10))
plt.show()

sns.heatmap(df.drop('Date', axis=1).corr(), annot=True, cmap='coolwarm')
plt.show()

df.info()

df.tail()

df.shape

sns.algorithms

print(sns.__doc__)

df.info()

df.describe()

df.iloc()

df.isnull()

from sklearn.model_selection import train_test_split

df.columns

df.x=df.drop('Date',axis=1)

X=df.drop('Date',axis=1)

X

y_1=df['Date']

y

import matplotlib.pyplot as plt
df_plot_data = df[['Open', 'Adj Close']].dropna()
X_plot = df_plot_data['Open']
y_plot = df_plot_data['Adj Close']
plt.figure(figsize=(10, 6))
plt.scatter(X_plot, y_plot, s=20, edgecolor="black", c="darkorange", label="data")
plt.xlabel("Open Price")
plt.ylabel("Adjusted Close Price")
plt.title("Open Price vs Adjusted Close Price")
plt.legend()
plt.grid(True)
plt.show()

df.head()

df.info()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Prepare data, dropping rows with any missing values in relevant columns
df_model = df[['Open', 'Adj Close']].dropna()

# Define features (X) and target (y)
X_model = df_model[['Open']]
y_model = df_model['Adj Close']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_model, y_model, test_size=0.2, random_state=42)

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print(f"R-squared score: {r2:.4f}")
print(f"Mean Squared Error: {mse:.2f}")

# Optionally, visualize predictions vs actual values
plt.figure(figsize=(10, 6))
plt.scatter(X_test, y_test, color='blue', label='Actual Adjusted Close')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Predicted Adjusted Close')
plt.title('Linear Regression: Open Price vs Adjusted Close Price')
plt.xlabel('Open Price')
plt.ylabel('Adjusted Close Price')
plt.legend()
plt.grid(True)
plt.show()